### ISSUE TITLE
Include a dockerfile that builds for testnet

### ISSUE THREAD

**Issue by emielvanderhoek** [hicommonwealth/edgeware-node#3] opened 2018-12-14 14:01 UTC
Include a dockerfile that builds for testnet
Related to issue: #1
Relevant for support in Polkascan & Polkasource

**Comment by jnaviask** [comment] 2018-12-17 16:13
This basic dockerfile works and gets it up with the `--dev` flag. Still need to figure out what arguments we need to get it directly on the testnet, but close to resolving this issue. https://github.com/hicommonwealth/edgeware-node/blob/master/Dockerfile

**Comment by emielvanderhoek** [comment] 2018-12-18 08:15
Are you sure, I am running into this error: 

> error: couldn't read src/../runtime/wasm/target/wasm32-unknown-unknown/release/edgeware_runtime.compact.wasm: No such file or directory (os error 2)
> --> src/chain_spec.rs:89:10
> code: include_bytes!("../runtime/wasm/target/wasm32-unknown-unknown/release/edgeware_runtime.compact.wasm").to_vec(),
> error: couldn't read src/../runtime/wasm/target/wasm32-unknown-unknown/release/edgeware_runtime.compact.wasm: No such file or directory (os error 2)
> --> src/service.rs:24:2
> include_bytes!("../runtime/wasm/target/wasm32-unknown-unknown/release/edgeware_runtime.compact.wasm")
> error: aborting due to 2 previous errors
> error: Could not compile `edgeware`.

**Comment by jnaviask** [comment] 2018-12-18 15:35
Ah, thanks for that -- looks like it was unintentionally pulling in my local wasm build. I'll get a fix out ASAP.

**Comment by emielvanderhoek** [comment] 2018-12-20 14:00
Any updates?

**Comment by jnaviask** [comment] 2018-12-20 17:04
Got stuck figuring out how to set up the tooling needed for the WASM build. I can take another stab at it soon.

**Comment by jnaviask** [comment] 2018-12-20 21:06
This commit should fix the problem by also invoking a build of the WASM runtime: https://github.com/hicommonwealth/edgeware-node/commit/f12ce959a5c7e82c52dd6ec93abdaab418d724f6

Give it a go, if it works then I can mark this one resolved.

**Comment by emielvanderhoek** [comment] 2018-12-21 10:53
hmm still errors...

Step 15/25 : RUN cd /edgeware/runtime/wasm && ./build.sh
 ---> Running in 9be0e0f5d4ca
error: failed to parse manifest at `/edgeware/runtime/wasm/Cargo.toml`

Caused by:
  can't find library `edgeware-runtime`, rename file to `src/lib.rs` or specify lib.path
The command '/bin/sh -c cd /edgeware/runtime/wasm && ./build.sh' returned a non-zero code: 101

**Comment by jnaviask** [comment] 2018-12-21 16:16
Very strange error... did you do the `docker build` with `--no-cache`? I'll try to reproduce in a clean clone of the repo.

**Comment by emielvanderhoek** [comment] 2019-01-06 23:33
I managed to build. I had to replace the symlink in "edgeware-node/runtime/wasm/src" with an actual copy of the folder is was referring to in order for the docker build process to complete.

In addition I had to make the edgeware-testnet.json chainspec file available in the docker. These two issues need further attention.

**Comment by jnaviask** [comment] 2019-01-07 19:37
This PR should fix the chainspec availability problem: https://github.com/hicommonwealth/edgeware-node/pull/21 but I was unable to reproduce the symlink issue.

**Closed** 2021-05-03 07:53 UTC
